version: "3"

services:
  consulta-ms:
    container_name: houm-service
    build:
        context: ./
        dockerfile: docker/dev.Dockerfile
    command: npm run dev
    depends_on:
      - mongo
    volumes:
      - ./src:/home/app/src
      - ./nodemon.json:/home/app/nodemon.json
    ports: 
      - '5002:5002'

  mongo:
    container_name: houm-mongo
    image: mongo
    command: mongod --port 27020
    ports: ['27020:27020']
    volumes:
      - ./data:/data/db